apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana
  namespace: monitoring
  labels:
    name: prometheus
spec:
  selector:
    app: prometheus
  type: LoadBalancer
  ports:
    - name: prometheus
      port: 8888
      targetPort: 3000
