apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: back-hpa
spec: 
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment 
    name: back-deploy # backend Deployment와 연결 
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
