---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: deploy
  name: efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

